### ISSUE TITLE
found a typo

### ISSUE THREAD

**Issue by thoughtcastapp** [HenestrosaConH/ios-interview-questions#2]
I believe the second question should be how to explain MVC to a new developer:
<img width="744" alt="image" src="https://user-images.githubusercontent.com/38260217/235784608-09605055-ca4e-46f6-9c34-08752ed60b19.png">

Ty for putting together this resource, I have learned quite a bit from it already!

**Comment by HenestrosaConH** [comment]
You're right! I've fixed it now. Thanks for pointing it out :)
